### ISSUE TITLE
cy.task is not a function

### ISSUE THREAD

**Issue by lazarljubenovic** [palmerhq/cypress-image-snapshot#28]
I've followed the instructions from the readme, but I'm getting the following.

```text
cypress_runner.js:139349 TypeError: cy.task is not a function
    at Context.matchImageSnapshot (http://localhost:8081/__cypress/tests?p=tests/e2e/support/index.js-677:26:8)
From previous event:
    at runCommand (http://localhost:8081/__cypress/runner/cypress_runner.js:63043:14)
    at next (http://localhost:8081/__cypress/runner/cypress_runner.js:63125:14)
From previous event:
    at http://localhost:8081/__cypress/runner/cypress_runner.js:63144:37
From previous event:
    at run (http://localhost:8081/__cypress/runner/cypress_runner.js:63142:15)
    at Object.cy.(anonymous function) [as matchImageSnapshot] (http://localhost:8081/__cypress/runner/cypress_runner.js:63362:11)
    at Context.runnable.fn (http://localhost:8081/__cypress/runner/cypress_runner.js:63493:20)
    at callFn (http://localhost:8081/__cypress/runner/cypress_runner.js:33042:21)
    at Test.Runnable.run (http://localhost:8081/__cypress/runner/cypress_runner.js:33035:7)
    at http://localhost:8081/__cypress/runner/cypress_runner.js:66382:28
From previous event:
    at Object.onRunnableRun (http://localhost:8081/__cypress/runner/cypress_runner.js:66381:20)
    at $Cypress.action (http://localhost:8081/__cypress/runner/cypress_runner.js:61845:51)
    at Test.Runnable.run (http://localhost:8081/__cypress/runner/cypress_runner.js:65521:20)
    at Runner.runTest (http://localhost:8081/__cypress/runner/cypress_runner.js:33505:10)
    at http://localhost:8081/__cypress/runner/cypress_runner.js:33611:12
    at next (http://localhost:8081/__cypress/runner/cypress_runner.js:33425:14)
    at http://localhost:8081/__cypress/runner/cypress_runner.js:33435:7
    at next (http://localhost:8081/__cypress/runner/cypress_runner.js:33367:14)
    at http://localhost:8081/__cypress/runner/cypress_runner.js:33403:5
    at timeslice (http://localhost:8081/__cypress/runner/cypress_runner.js:28644:27)
```

I'm using Vue's CLI and its plugin for cypress, if that's of any help.

Here are my complete files which I think are relevant. The project is private so I cannot share it, but I can try reproducing later if needed -- thought it might be obvious from the stack trace to the maintainers, so wanted to avoid setting everything up.

**plugins/index.js**

```js
const { addMatchImageSnapshotPlugin } = require('cypress-image-snapshot/plugin')
module.exports = (on, config) => {
  addMatchImageSnapshotPlugin(on)
  return Object.assign({}, config, {
    fixturesFolder: 'tests/e2e/fixtures',
    integrationFolder: 'tests/e2e/specs',
    screenshotsFolder: 'tests/e2e/screenshots',
    videosFolder: 'tests/e2e/videos',
    supportFile: 'tests/e2e/support/index.js'
  })
}
```

(The return and Object.assign were there form Vue's scaffolding).

**support/commands.js**

```js
import { addMatchImageSnapshotCommand } from 'cypress-image-snapshot/command'
addMatchImageSnapshotCommand()
```

(This file was previously empty from Vue's scaffolding)

**specs/public-pages.js**

```js
describe(`Public pages`, () => {
    before(() => {
        cy.visit('/') })

    describe(`Login page`, () => {
        it(`is the first page user sees when not logged in`, () => {
            cy.url().should('contain', '/login') })
        it(`looks as per design`, () => {
            cy.matchImageSnapshot() })
        it(`should have a link to Forgot password page`, () => {
            cy.get('a[href="/forgot-password"]')
                .should('exist')
                .contains(`Forgot Password?`)
                .click() }) })

    describe(`Forgot Password page`, () => {
        it(`opens after clicking the link from Login`, () => {
            cy.url().should('contain', '/forgot-password') })
        it(`looks as per design`, () => {
            cy.matchImageSnapshot() }) }) })
```
And here are the results:

![image](https://user-images.githubusercontent.com/7661457/45074582-4b783000-b0e4-11e8-9b44-574c1dc5ce54.png)

![image](https://user-images.githubusercontent.com/7661457/45074586-516e1100-b0e4-11e8-9427-9d6e5025150e.png)

**Comment by crosscompile** [comment]
Which version of Cypress are you using?  `cy.task` was added in [3.0.0](https://docs.cypress.io/guides/references/changelog.html#3-0-0) so that could be the issue.

**Comment by lazarljubenovic** [comment]
I'll have to check it out in details. The Cypres version is, unfortunately, hidden behind a Vue CLI plugin.

![image](https://user-images.githubusercontent.com/7661457/45100889-9ae14f00-b12a-11e8-9212-d186b1d564b8.png)

**Comment by lazarljubenovic** [comment]
Yup, after upgrading the Cypress plugin, it installed 3.1.0 of Cypress and it's all working now. Thank you for the quick response!
